apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: ticketing
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  namespace: ticketing
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: ticketing
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: ticketing
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: ticketing
automountServiceAccountToken: false
